// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: block_packet.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxLocation int32

const (
	TxLocation_InBlock         TxLocation = 0
	TxLocation_InCandidatePool TxLocation = 1
	TxLocation_Missing         TxLocation = 2
)

// Enum value maps for TxLocation.
var (
	TxLocation_name = map[int32]string{
		0: "InBlock",
		1: "InCandidatePool",
		2: "Missing",
	}
	TxLocation_value = map[string]int32{
		"InBlock":         0,
		"InCandidatePool": 1,
		"Missing":         2,
	}
)

func (x TxLocation) Enum() *TxLocation {
	p := new(TxLocation)
	*p = x
	return p
}

func (x TxLocation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxLocation) Descriptor() protoreflect.EnumDescriptor {
	return file_block_packet_proto_enumTypes[0].Descriptor()
}

func (TxLocation) Type() protoreflect.EnumType {
	return &file_block_packet_proto_enumTypes[0]
}

func (x TxLocation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxLocation.Descriptor instead.
func (TxLocation) EnumDescriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{0}
}

type GetHeightestBlockSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *GetHeightestBlockSq) Reset() {
	*x = GetHeightestBlockSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHeightestBlockSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeightestBlockSq) ProtoMessage() {}

func (x *GetHeightestBlockSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeightestBlockSq.ProtoReflect.Descriptor instead.
func (*GetHeightestBlockSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{0}
}

func (x *GetHeightestBlockSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type GetHeightestBlockCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	Height uint32        `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
}

func (x *GetHeightestBlockCq) Reset() {
	*x = GetHeightestBlockCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHeightestBlockCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeightestBlockCq) ProtoMessage() {}

func (x *GetHeightestBlockCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeightestBlockCq.ProtoReflect.Descriptor instead.
func (*GetHeightestBlockCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{1}
}

func (x *GetHeightestBlockCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *GetHeightestBlockCq) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type NewBlockSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master        *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	BlockFilename string        `protobuf:"bytes,2,opt,name=BlockFilename,proto3" json:"BlockFilename,omitempty"`
}

func (x *NewBlockSq) Reset() {
	*x = NewBlockSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewBlockSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBlockSq) ProtoMessage() {}

func (x *NewBlockSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBlockSq.ProtoReflect.Descriptor instead.
func (*NewBlockSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{2}
}

func (x *NewBlockSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *NewBlockSq) GetBlockFilename() string {
	if x != nil {
		return x.BlockFilename
	}
	return ""
}

type NewBlockCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *NewBlockCq) Reset() {
	*x = NewBlockCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewBlockCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBlockCq) ProtoMessage() {}

func (x *NewBlockCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBlockCq.ProtoReflect.Descriptor instead.
func (*NewBlockCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{3}
}

func (x *NewBlockCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type GetBlockSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master  *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	BlockId uint32        `protobuf:"varint,2,opt,name=BlockId,proto3" json:"BlockId,omitempty"`
}

func (x *GetBlockSq) Reset() {
	*x = GetBlockSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockSq) ProtoMessage() {}

func (x *GetBlockSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockSq.ProtoReflect.Descriptor instead.
func (*GetBlockSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlockSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *GetBlockSq) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

type GetBlockCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *GetBlockCq) Reset() {
	*x = GetBlockCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockCq) ProtoMessage() {}

func (x *GetBlockCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockCq.ProtoReflect.Descriptor instead.
func (*GetBlockCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlockCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type SendBlockSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master        *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	BlockFilename string        `protobuf:"bytes,2,opt,name=BlockFilename,proto3" json:"BlockFilename,omitempty"`
}

func (x *SendBlockSq) Reset() {
	*x = SendBlockSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBlockSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBlockSq) ProtoMessage() {}

func (x *SendBlockSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBlockSq.ProtoReflect.Descriptor instead.
func (*SendBlockSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{6}
}

func (x *SendBlockSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *SendBlockSq) GetBlockFilename() string {
	if x != nil {
		return x.BlockFilename
	}
	return ""
}

type SendBlockCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *SendBlockCq) Reset() {
	*x = SendBlockCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBlockCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBlockCq) ProtoMessage() {}

func (x *SendBlockCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBlockCq.ProtoReflect.Descriptor instead.
func (*SendBlockCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{7}
}

func (x *SendBlockCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type SendTransactionSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	TxId   []byte        `protobuf:"bytes,2,opt,name=TxId,proto3" json:"TxId,omitempty"`
}

func (x *SendTransactionSq) Reset() {
	*x = SendTransactionSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransactionSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionSq) ProtoMessage() {}

func (x *SendTransactionSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionSq.ProtoReflect.Descriptor instead.
func (*SendTransactionSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{8}
}

func (x *SendTransactionSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *SendTransactionSq) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

type SendTransactionCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *SendTransactionCq) Reset() {
	*x = SendTransactionCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransactionCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionCq) ProtoMessage() {}

func (x *SendTransactionCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionCq.ProtoReflect.Descriptor instead.
func (*SendTransactionCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{9}
}

func (x *SendTransactionCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type SendDataTransactionSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master   *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	TxId     []byte        `protobuf:"bytes,2,opt,name=TxId,proto3" json:"TxId,omitempty"`
	DataTxId []byte        `protobuf:"bytes,3,opt,name=DataTxId,proto3" json:"DataTxId,omitempty"`
}

func (x *SendDataTransactionSq) Reset() {
	*x = SendDataTransactionSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDataTransactionSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDataTransactionSq) ProtoMessage() {}

func (x *SendDataTransactionSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDataTransactionSq.ProtoReflect.Descriptor instead.
func (*SendDataTransactionSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{10}
}

func (x *SendDataTransactionSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *SendDataTransactionSq) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

func (x *SendDataTransactionSq) GetDataTxId() []byte {
	if x != nil {
		return x.DataTxId
	}
	return nil
}

type SendDataTransactionCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *SendDataTransactionCq) Reset() {
	*x = SendDataTransactionCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDataTransactionCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDataTransactionCq) ProtoMessage() {}

func (x *SendDataTransactionCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDataTransactionCq.ProtoReflect.Descriptor instead.
func (*SendDataTransactionCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{11}
}

func (x *SendDataTransactionCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type SearchTransactionSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master  *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	Address []byte        `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Type    uint32        `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *SearchTransactionSq) Reset() {
	*x = SearchTransactionSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTransactionSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTransactionSq) ProtoMessage() {}

func (x *SearchTransactionSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTransactionSq.ProtoReflect.Descriptor instead.
func (*SearchTransactionSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{12}
}

func (x *SearchTransactionSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *SearchTransactionSq) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *SearchTransactionSq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type SearchTransactionCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *SearchTransactionCq) Reset() {
	*x = SearchTransactionCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTransactionCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTransactionCq) ProtoMessage() {}

func (x *SearchTransactionCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTransactionCq.ProtoReflect.Descriptor instead.
func (*SearchTransactionCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{13}
}

func (x *SearchTransactionCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type GetDataTxIdListSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master  *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	BlockId uint32        `protobuf:"varint,2,opt,name=BlockId,proto3" json:"BlockId,omitempty"`
	Skip    uint32        `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Take    uint32        `protobuf:"varint,4,opt,name=take,proto3" json:"take,omitempty"`
	PubKey  []byte        `protobuf:"bytes,5,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
}

func (x *GetDataTxIdListSq) Reset() {
	*x = GetDataTxIdListSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataTxIdListSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataTxIdListSq) ProtoMessage() {}

func (x *GetDataTxIdListSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataTxIdListSq.ProtoReflect.Descriptor instead.
func (*GetDataTxIdListSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{14}
}

func (x *GetDataTxIdListSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *GetDataTxIdListSq) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *GetDataTxIdListSq) GetSkip() uint32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetDataTxIdListSq) GetTake() uint32 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *GetDataTxIdListSq) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

type GetDataTxIdListCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *GetDataTxIdListCq) Reset() {
	*x = GetDataTxIdListCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataTxIdListCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataTxIdListCq) ProtoMessage() {}

func (x *GetDataTxIdListCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataTxIdListCq.ProtoReflect.Descriptor instead.
func (*GetDataTxIdListCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{15}
}

func (x *GetDataTxIdListCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type SendDataTxIdListSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master   *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	DataTxId []byte        `protobuf:"bytes,2,opt,name=DataTxId,proto3" json:"DataTxId,omitempty"`
	BlockId  uint32        `protobuf:"varint,3,opt,name=BlockId,proto3" json:"BlockId,omitempty"`
	PubKey   []byte        `protobuf:"bytes,4,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
}

func (x *SendDataTxIdListSq) Reset() {
	*x = SendDataTxIdListSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDataTxIdListSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDataTxIdListSq) ProtoMessage() {}

func (x *SendDataTxIdListSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDataTxIdListSq.ProtoReflect.Descriptor instead.
func (*SendDataTxIdListSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{16}
}

func (x *SendDataTxIdListSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *SendDataTxIdListSq) GetDataTxId() []byte {
	if x != nil {
		return x.DataTxId
	}
	return nil
}

func (x *SendDataTxIdListSq) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *SendDataTxIdListSq) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

type SendDataTxIdListCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *SendDataTxIdListCq) Reset() {
	*x = SendDataTxIdListCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDataTxIdListCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDataTxIdListCq) ProtoMessage() {}

func (x *SendDataTxIdListCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDataTxIdListCq.ProtoReflect.Descriptor instead.
func (*SendDataTxIdListCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{17}
}

func (x *SendDataTxIdListCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type GetBlockHashSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master  *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	BlockId uint32        `protobuf:"varint,2,opt,name=BlockId,proto3" json:"BlockId,omitempty"`
}

func (x *GetBlockHashSq) Reset() {
	*x = GetBlockHashSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockHashSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHashSq) ProtoMessage() {}

func (x *GetBlockHashSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHashSq.ProtoReflect.Descriptor instead.
func (*GetBlockHashSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{18}
}

func (x *GetBlockHashSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *GetBlockHashSq) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

type GetBlockHashCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *GetBlockHashCq) Reset() {
	*x = GetBlockHashCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockHashCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHashCq) ProtoMessage() {}

func (x *GetBlockHashCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHashCq.ProtoReflect.Descriptor instead.
func (*GetBlockHashCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{19}
}

func (x *GetBlockHashCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type SendBlockHashSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	Hash   []byte        `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *SendBlockHashSq) Reset() {
	*x = SendBlockHashSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBlockHashSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBlockHashSq) ProtoMessage() {}

func (x *SendBlockHashSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBlockHashSq.ProtoReflect.Descriptor instead.
func (*SendBlockHashSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{20}
}

func (x *SendBlockHashSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *SendBlockHashSq) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type SendBlockHashCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *SendBlockHashCq) Reset() {
	*x = SendBlockHashCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBlockHashCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBlockHashCq) ProtoMessage() {}

func (x *SendBlockHashCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBlockHashCq.ProtoReflect.Descriptor instead.
func (*SendBlockHashCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{21}
}

func (x *SendBlockHashCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type GetBlockPrevHashSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master  *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	BlockId uint32        `protobuf:"varint,2,opt,name=BlockId,proto3" json:"BlockId,omitempty"`
}

func (x *GetBlockPrevHashSq) Reset() {
	*x = GetBlockPrevHashSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockPrevHashSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockPrevHashSq) ProtoMessage() {}

func (x *GetBlockPrevHashSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockPrevHashSq.ProtoReflect.Descriptor instead.
func (*GetBlockPrevHashSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{22}
}

func (x *GetBlockPrevHashSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *GetBlockPrevHashSq) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

type GetBlockPrevHashCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *GetBlockPrevHashCq) Reset() {
	*x = GetBlockPrevHashCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockPrevHashCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockPrevHashCq) ProtoMessage() {}

func (x *GetBlockPrevHashCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockPrevHashCq.ProtoReflect.Descriptor instead.
func (*GetBlockPrevHashCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{23}
}

func (x *GetBlockPrevHashCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type SendBlockPrevHashSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	Hash   []byte        `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *SendBlockPrevHashSq) Reset() {
	*x = SendBlockPrevHashSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBlockPrevHashSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBlockPrevHashSq) ProtoMessage() {}

func (x *SendBlockPrevHashSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBlockPrevHashSq.ProtoReflect.Descriptor instead.
func (*SendBlockPrevHashSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{24}
}

func (x *SendBlockPrevHashSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *SendBlockPrevHashSq) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type SendBlockPrevHashCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *SendBlockPrevHashCq) Reset() {
	*x = SendBlockPrevHashCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBlockPrevHashCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBlockPrevHashCq) ProtoMessage() {}

func (x *SendBlockPrevHashCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBlockPrevHashCq.ProtoReflect.Descriptor instead.
func (*SendBlockPrevHashCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{25}
}

func (x *SendBlockPrevHashCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type GetTxStatusSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	TxId   []byte        `protobuf:"bytes,2,opt,name=TxId,proto3" json:"TxId,omitempty"`
}

func (x *GetTxStatusSq) Reset() {
	*x = GetTxStatusSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTxStatusSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxStatusSq) ProtoMessage() {}

func (x *GetTxStatusSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxStatusSq.ProtoReflect.Descriptor instead.
func (*GetTxStatusSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{26}
}

func (x *GetTxStatusSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *GetTxStatusSq) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

type GetTxStatusCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *GetTxStatusCq) Reset() {
	*x = GetTxStatusCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTxStatusCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxStatusCq) ProtoMessage() {}

func (x *GetTxStatusCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxStatusCq.ProtoReflect.Descriptor instead.
func (*GetTxStatusCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{27}
}

func (x *GetTxStatusCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

type SendTxStatusSq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master  *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
	TxId    []byte        `protobuf:"bytes,2,opt,name=TxId,proto3" json:"TxId,omitempty"`
	BlockId uint32        `protobuf:"varint,3,opt,name=BlockId,proto3" json:"BlockId,omitempty"`
	TxLoc   TxLocation    `protobuf:"varint,4,opt,name=TxLoc,proto3,enum=ghostnet.packets.TxLocation" json:"TxLoc,omitempty"`
}

func (x *SendTxStatusSq) Reset() {
	*x = SendTxStatusSq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTxStatusSq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTxStatusSq) ProtoMessage() {}

func (x *SendTxStatusSq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTxStatusSq.ProtoReflect.Descriptor instead.
func (*SendTxStatusSq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{28}
}

func (x *SendTxStatusSq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *SendTxStatusSq) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

func (x *SendTxStatusSq) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *SendTxStatusSq) GetTxLoc() TxLocation {
	if x != nil {
		return x.TxLoc
	}
	return TxLocation_InBlock
}

type SendTxStatusCq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master *MasterPacket `protobuf:"bytes,1,opt,name=Master,proto3" json:"Master,omitempty"`
}

func (x *SendTxStatusCq) Reset() {
	*x = SendTxStatusCq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_packet_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTxStatusCq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTxStatusCq) ProtoMessage() {}

func (x *SendTxStatusCq) ProtoReflect() protoreflect.Message {
	mi := &file_block_packet_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTxStatusCq.ProtoReflect.Descriptor instead.
func (*SendTxStatusCq) Descriptor() ([]byte, []int) {
	return file_block_packet_proto_rawDescGZIP(), []int{29}
}

func (x *SendTxStatusCq) GetMaster() *MasterPacket {
	if x != nil {
		return x.Master
	}
	return nil
}

var File_block_packet_proto protoreflect.FileDescriptor

var file_block_packet_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x65, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x53, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x65, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x65, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43,
	0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x6a, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x71, 0x12,
	0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a,
	0x0a, 0x4e, 0x65, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x22, 0x5e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53,
	0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43,
	0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x6b, 0x0a, 0x0b, 0x53, 0x65, 0x6e,
	0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x24, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x45, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x43, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74,
	0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x5f, 0x0a,
	0x11, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x78,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x54, 0x78, 0x49, 0x64, 0x22, 0x4b,
	0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x7f, 0x0a, 0x15, 0x53,
	0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x78, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x54, 0x78, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x78, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x78, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x15,
	0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74,
	0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x7b, 0x0a,
	0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4d, 0x0a, 0x13, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0xa5, 0x01, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x54, 0x78, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x71, 0x12,
	0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x73, 0x6b, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x6b, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x62,
	0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x50, 0x75, 0x62, 0x4b, 0x65,
	0x79, 0x22, 0x4b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x54, 0x78, 0x49, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65,
	0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x9a,
	0x01, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x54, 0x78, 0x49, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74,
	0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x78, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x78, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x4c, 0x0a, 0x12, 0x53,
	0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x54, 0x78, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x62, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x53, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x48, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x43, 0x71, 0x12,
	0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x5d, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x53, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x49, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x43, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x22, 0x66, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x65,
	0x76, 0x48, 0x61, 0x73, 0x68, 0x53, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e,
	0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x65, 0x76, 0x48, 0x61, 0x73, 0x68, 0x43, 0x71, 0x12,
	0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x61, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x65, 0x76, 0x48, 0x61, 0x73, 0x68, 0x53, 0x71, 0x12, 0x36,
	0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x4d, 0x0a, 0x13, 0x53, 0x65,
	0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x65, 0x76, 0x48, 0x61, 0x73, 0x68, 0x43,
	0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x78, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x54, 0x78, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x78, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e,
	0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22,
	0xaa, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x53, 0x71, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x78,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x54, 0x78, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x05, 0x54, 0x78, 0x4c, 0x6f,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e,
	0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x54, 0x78, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x54, 0x78, 0x4c, 0x6f, 0x63, 0x22, 0x48, 0x0a, 0x0e,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x71, 0x12, 0x36,
	0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2a, 0x3b, 0x0a, 0x0a, 0x54, 0x78, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x6e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x6f, 0x6c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e,
	0x67, 0x10, 0x02, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x47, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x65, 0x74, 0x2d, 0x44, 0x65, 0x76, 0x2f, 0x47,
	0x68, 0x6f, 0x73, 0x74, 0x4e, 0x65, 0x74, 0x2d, 0x43, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_block_packet_proto_rawDescOnce sync.Once
	file_block_packet_proto_rawDescData = file_block_packet_proto_rawDesc
)

func file_block_packet_proto_rawDescGZIP() []byte {
	file_block_packet_proto_rawDescOnce.Do(func() {
		file_block_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_block_packet_proto_rawDescData)
	})
	return file_block_packet_proto_rawDescData
}

var file_block_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_block_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_block_packet_proto_goTypes = []interface{}{
	(TxLocation)(0),               // 0: ghostnet.packets.TxLocation
	(*GetHeightestBlockSq)(nil),   // 1: ghostnet.packets.GetHeightestBlockSq
	(*GetHeightestBlockCq)(nil),   // 2: ghostnet.packets.GetHeightestBlockCq
	(*NewBlockSq)(nil),            // 3: ghostnet.packets.NewBlockSq
	(*NewBlockCq)(nil),            // 4: ghostnet.packets.NewBlockCq
	(*GetBlockSq)(nil),            // 5: ghostnet.packets.GetBlockSq
	(*GetBlockCq)(nil),            // 6: ghostnet.packets.GetBlockCq
	(*SendBlockSq)(nil),           // 7: ghostnet.packets.SendBlockSq
	(*SendBlockCq)(nil),           // 8: ghostnet.packets.SendBlockCq
	(*SendTransactionSq)(nil),     // 9: ghostnet.packets.SendTransactionSq
	(*SendTransactionCq)(nil),     // 10: ghostnet.packets.SendTransactionCq
	(*SendDataTransactionSq)(nil), // 11: ghostnet.packets.SendDataTransactionSq
	(*SendDataTransactionCq)(nil), // 12: ghostnet.packets.SendDataTransactionCq
	(*SearchTransactionSq)(nil),   // 13: ghostnet.packets.SearchTransactionSq
	(*SearchTransactionCq)(nil),   // 14: ghostnet.packets.SearchTransactionCq
	(*GetDataTxIdListSq)(nil),     // 15: ghostnet.packets.GetDataTxIdListSq
	(*GetDataTxIdListCq)(nil),     // 16: ghostnet.packets.GetDataTxIdListCq
	(*SendDataTxIdListSq)(nil),    // 17: ghostnet.packets.SendDataTxIdListSq
	(*SendDataTxIdListCq)(nil),    // 18: ghostnet.packets.SendDataTxIdListCq
	(*GetBlockHashSq)(nil),        // 19: ghostnet.packets.GetBlockHashSq
	(*GetBlockHashCq)(nil),        // 20: ghostnet.packets.GetBlockHashCq
	(*SendBlockHashSq)(nil),       // 21: ghostnet.packets.SendBlockHashSq
	(*SendBlockHashCq)(nil),       // 22: ghostnet.packets.SendBlockHashCq
	(*GetBlockPrevHashSq)(nil),    // 23: ghostnet.packets.GetBlockPrevHashSq
	(*GetBlockPrevHashCq)(nil),    // 24: ghostnet.packets.GetBlockPrevHashCq
	(*SendBlockPrevHashSq)(nil),   // 25: ghostnet.packets.SendBlockPrevHashSq
	(*SendBlockPrevHashCq)(nil),   // 26: ghostnet.packets.SendBlockPrevHashCq
	(*GetTxStatusSq)(nil),         // 27: ghostnet.packets.GetTxStatusSq
	(*GetTxStatusCq)(nil),         // 28: ghostnet.packets.GetTxStatusCq
	(*SendTxStatusSq)(nil),        // 29: ghostnet.packets.SendTxStatusSq
	(*SendTxStatusCq)(nil),        // 30: ghostnet.packets.SendTxStatusCq
	(*MasterPacket)(nil),          // 31: ghostnet.packets.MasterPacket
}
var file_block_packet_proto_depIdxs = []int32{
	31, // 0: ghostnet.packets.GetHeightestBlockSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 1: ghostnet.packets.GetHeightestBlockCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 2: ghostnet.packets.NewBlockSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 3: ghostnet.packets.NewBlockCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 4: ghostnet.packets.GetBlockSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 5: ghostnet.packets.GetBlockCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 6: ghostnet.packets.SendBlockSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 7: ghostnet.packets.SendBlockCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 8: ghostnet.packets.SendTransactionSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 9: ghostnet.packets.SendTransactionCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 10: ghostnet.packets.SendDataTransactionSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 11: ghostnet.packets.SendDataTransactionCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 12: ghostnet.packets.SearchTransactionSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 13: ghostnet.packets.SearchTransactionCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 14: ghostnet.packets.GetDataTxIdListSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 15: ghostnet.packets.GetDataTxIdListCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 16: ghostnet.packets.SendDataTxIdListSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 17: ghostnet.packets.SendDataTxIdListCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 18: ghostnet.packets.GetBlockHashSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 19: ghostnet.packets.GetBlockHashCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 20: ghostnet.packets.SendBlockHashSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 21: ghostnet.packets.SendBlockHashCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 22: ghostnet.packets.GetBlockPrevHashSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 23: ghostnet.packets.GetBlockPrevHashCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 24: ghostnet.packets.SendBlockPrevHashSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 25: ghostnet.packets.SendBlockPrevHashCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 26: ghostnet.packets.GetTxStatusSq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 27: ghostnet.packets.GetTxStatusCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // 28: ghostnet.packets.SendTxStatusSq.Master:type_name -> ghostnet.packets.MasterPacket
	0,  // 29: ghostnet.packets.SendTxStatusSq.TxLoc:type_name -> ghostnet.packets.TxLocation
	31, // 30: ghostnet.packets.SendTxStatusCq.Master:type_name -> ghostnet.packets.MasterPacket
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_block_packet_proto_init() }
func file_block_packet_proto_init() {
	if File_block_packet_proto != nil {
		return
	}
	file_common_packet_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_block_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHeightestBlockSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHeightestBlockCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewBlockSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewBlockCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBlockSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBlockCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransactionSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransactionCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDataTransactionSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDataTransactionCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTransactionSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTransactionCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataTxIdListSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataTxIdListCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDataTxIdListSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDataTxIdListCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockHashSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockHashCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBlockHashSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBlockHashCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockPrevHashSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockPrevHashCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBlockPrevHashSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBlockPrevHashCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTxStatusSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTxStatusCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTxStatusSq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_packet_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTxStatusCq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_block_packet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_packet_proto_goTypes,
		DependencyIndexes: file_block_packet_proto_depIdxs,
		EnumInfos:         file_block_packet_proto_enumTypes,
		MessageInfos:      file_block_packet_proto_msgTypes,
	}.Build()
	File_block_packet_proto = out.File
	file_block_packet_proto_rawDesc = nil
	file_block_packet_proto_goTypes = nil
	file_block_packet_proto_depIdxs = nil
}
